export default [
  'Acessórios para Veículos',
  'Agro',
  'Alimentos e Bebidas',
  'Animais',
  'Antiguidades e Coleções',
  'Arte, Papelaria e Armarinho',
  'Bebês',
  'Beleza e Cuidado Pessoal',
  'Brinquedos e Hobbies',
  'Calçados, Roupas e Bolsas',
  'Carros, Motos e Outros',
  'Casa, Móveis e Decoração',
  'Celulares e Telefones',
  'Câmeras e Acessórios',
  'Eletrodomésticos',
  'Eletrônicos, Áudio e Vídeo',
  'Esportes e Fitness',
  'Ferramentas e Construção',
  'Festas e Lembrancinhas',
  'Games',
  'Indústria e Comércio',
  'Informática',
  'Ingressos',
  'Instrumentos Musicais',
  'Joias e Relógios',
  'Livros, Revistas e Comics',
  'Música, Filmes e Seriados',
  'Saúde',
];
